name: Run playwright in Docker

on:
  workflow_dispatch:

jobs:
  visual-admin:
    runs-on: ubuntu-24.04

    steps:
      - name: Define environment
        shell: bash
        run: |
            echo "FEATURE_ALL=${{ inputs.major && 'major' }}" >> $GITHUB_ENV
            echo "REDIS_URL=redis://localhost:6379" >> $GITHUB_ENV
            echo "MAILER_DSN=smtp://localhost:1025" >> $GITHUB_ENV
            echo "MAILPIT_BASE_URL=http://localhost:8025" >> $GITHUB_ENV
            echo "SHOPWARE_HTTP_CACHE_ENABLED=0" >> $GITHUB_ENV
            echo "SHOPWARE_DISABLE_UPDATE_CHECK=true" >> $GITHUB_ENV
            echo "BLUE_GREEN_DEPLOYMENT=1" >> $GITHUB_ENV
            echo "ENABLE_SERVICES=0" >> $GITHUB_ENV

      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
            env: prod
            mysql-version: "builtin"
            shopware-version: v6.7.10.0
            shopware-repository: shopware/shopware
            install: true
            install-admin: true
            install-storefront: true

      # - name: Stop mysql and symfony server
      #   run: |
      #     sudo systemctl stop mysql
      #     symfony server:stop   

      - name: Install Playwright dependencies
        working-directory: tests/acceptance
        run: npm ci

      #- name: Start Shopware containers
      #  run: docker compose up -d

      - name: Run visual tests in Playwright container
        working-directory: tests/acceptance
        run: |
          # docker compose up -d
          # docker compose ps
          # docker compose run -d web #no such service called web
          docker run --rm \
            --ipc=host \
            --init \
            --network=host \
            # --add-host=host.docker.internal:host-gateway \
            -e APP_URL=http://host.docker.internal:8000 \
            -e SHOPWARE_ADMIN_USERNAME=admin \
            -e SHOPWARE_ADMIN_PASSWORD=shopware \
            -v "$GITHUB_WORKSPACE:/app" \
            -w /app/tests/acceptance \
            mcr.microsoft.com/playwright:v1.58.1-noble \
            npx playwright test --project=Visual --grep Storefront

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: |
            tests/acceptance/test-results/
            tests/acceptance/playwright-report/
          retention-days: 3
